### ISSUE TITLE
Support Flux instances with access to namespaces other than their own

### ISSUE THREAD

**Issue by tobad357** [justinbarrick/flux-operator#29]
Some questions and an issue

1. If running namespaces flux operators
    Example:
        flux-dev  for dev namespace
        flux-staging for staging namespace
   Is it recommended to run the operator in the same namespace as the applications or run them all in a main flux namespace?

2. When we enable a flux operator we get an error like this
```
secrets \"flux-git-dev-deploy\" is forbidden: User \"system:serviceaccount:flux:flux-dev\" cannot patch secrets in the namespace \"flux\": Unknown user \"system:serviceaccount:flux:flux-dev\"
```

We deployed the operator by doing kubectl apply -f on 
https://github.com/justinbarrick/flux-operator/blob/master/deploy/flux-operator-namespaced.yaml

**Comment by justinbarrick** [comment]
For question 1, I typically run the flux-operator in its own namespace and then each Flux would live in and control its own namespace.

So in your example, you would have a namespace called flux-dev with a Flux in it and a namespace called flux-staging with a Flux in it.

For 2, can you show me what the Flux you created was? Is the error from the flux-operator log?

**Comment by tobad357** [comment]
Yes the error is from the log

And the yaml is as follows

```
apiVersion: flux.codesink.net/v1alpha1
kind: Flux
metadata:
  name: dev
  namespace: flux-dev
spec:
  gitUrl: git@github.com:xxxx/yyyy.git
  gitBranch: master
  args:
    k8s-namespace-whitelist: dev
```

Log
```
ts=2018-08-27T02:44:10.706021586Z caller=main.go:140 version=1.5.0
ts=2018-08-27T02:44:10.967775007Z caller=main.go:222 err="secrets \"flux-git-dev-deploy\" is forbidden: User \"system:serviceaccount:flux-dev:flux-dev\" cannot patch secrets in the namespace \"flux-dev\": Unknown user \"system:serviceaccount:flux-dev:flux-dev\""
```
